#!/usr/bin/env ruby
$LOAD_PATH << './lib'

require 'longboat'

collector = Longboat::Collector.new

jobs = Longboat::Jobs.new
jobs.load(collector)
t = jobs.collect_every

require 'longboat/server'
Longboat::Server.serve!(collector)
