#!/usr/bin/env ruby
$LOAD_PATH << './lib'

require 'longboat'

# Handle command line options
config = Longboat::Config.parse!

# Start collection
collector = Longboat::Collector.new(config)
raiders = Longboat::Raiders.new(collector, config)
t = raiders.raid_every

# Serve metrics on HTTP
Longboat::Server.serve!(collector, config)
